[sources.my_source_id]
  type = "prometheus_scrape" # required
  endpoints = ["https://startup-olk-web.herokuapp.com/metrics"] # required
  scrape_interval_secs = 15 # optional, default, seconds

# [sources.my_source_id]
#   type = "docker_logs" # required
#   docker_host = "https://localhost:64608/" # optional, no default
  #include_containers = ["include_", "include_me_0", "ad08cc418cf9"] # optional, no default
  #include_images = ["httpd", "redis"] # optional, no default
  #include_labels = ["com.example.vendor=Timber Inc.", "com.example.name=Vector"] # optional, no default

[sinks.my_sink_id]
  # General
  type = "console" # required
  inputs = ["my_source_id"] # required
  target = "stdout" # optional, default
  encoding.codec = "json" # required


[sinks.my_sink_test]
  type = "prometheus_remote_write" # required
  inputs = ["my_source_id"] # required
  #default_namespace = "service" # optional, no default
  endpoint = "https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push" # required
  auth.password = "eyJrIjoiN2U3MDM2ODE1ODYyMjBlY2E3MjU1NzkzYjA3YzM0YTdiNTNiYjUyYSIsIm4iOiJjdnZ2IiwiaWQiOjQ4MDUzNX0=" # required
  auth.strategy = "basic" # required
  auth.user = "76369" # required

[sources.my_heroku_logs]
  type = "heroku_logs" # required
  address = "0.0.0.0:80" # required


[sinks.my_sink_id]
  # General
  type = "loki" # required
  inputs = ["my_heroku_logs"] # required
  endpoint = "https://logs-prod-us-central1.grafana.net" # required

  auth.strategy = "basic" # required
  auth.token = "eyJrIjoiN2U3MDM2ODE1ODYyMjBlY2E3MjU1NzkzYjA3YzM0YTdiNTNiYjUyYSIsIm4iOiJjdnZ2IiwiaWQiOjQ4MDUzNX0=" # required
  auth.user = "37161" # required

  # Encoding
  encoding.codec = "json" # required

  # Healthcheck
  # healthcheck.enabled = true # optional, default

  # Labels
  # labels.forwarder = "vector" # example
  # labels.event = "{{ event_field }}" # example
  # labels.key = "value" # example

[api]
enabled = true
address = "127.0.0.1:8899"